// =============================================
//  构建中文版角色数据库
//  1. 读 waifu-db.json
//  2. 人物名/作品名翻译 (已知角色直接映射)
//  3. 添加 25 个东方角色
//  4. 输出 waifu-db-zh.json
// =============================================

const fs = require('fs');
const path = require('path');

const DB_FILE = path.join(__dirname, '..', 'data', 'waifu-db.json');
const OUT_JSON = path.join(__dirname, '..', 'data', 'waifu-db-zh.json');
const OUT_JS = path.join(__dirname, '..', 'data', 'waifu-db-zh.js');

const db = JSON.parse(fs.readFileSync(DB_FILE, 'utf-8').replace(/^\uFEFF/, ''));

// ═══ 角色名中译映射 ═══
const nameMap = {
  'Emilia': '爱蜜莉雅',
  'Mikasa Ackerman': '三笠·阿克曼',
  'Kurisu Makise': '牧濑红莉栖',
  'Makima': '玛奇玛',
  'Mai Sakurajima': '樱岛麻衣',
  'Frieren': '芙莉莲',
  'Maomao': '猫猫',
  'Kaguya Shinomiya': '四宫辉夜',
  'Violet Evergarden': '薇尔莉特·伊芙加登',
  'Power': '帕瓦',
  'Asuna Yuuki': '结城明日奈',
  'Shinobu Kochou': '蝴蝶忍',
  'Mitsuri Kanroji': '甘露寺蜜璃',
  'Nezuko Kamado': '灶门祢豆子',
  'Rem': '雷姆',
  'Ram': '拉姆',
  'Megumin': '惠惠',
  'Aqua': '阿库娅',
  'Darkness': '达克妮丝',
  'Saber': '阿尔托莉雅·潘德拉贡',
  'Rin Tohsaka': '远坂凛',
  'Sakura Matou': '间桐樱',
  'Illyasviel von Einzbern': '伊莉雅丝菲尔·冯·爱因兹贝伦',
  'C.C.': 'C.C.',
  'Kallen Stadtfeld': '卡莲·休妲菲尔特',
  'Zero Two': '02',
  'Ichigo': '莓',
  'Yor Forger': '约尔·福杰',
  'Anya Forger': '阿尼亚·福杰',
  'Hinata Hyuuga': '日向雏田',
  'Sakura Haruno': '春野樱',
  'Tsunade': '纲手',
  'Nami': '娜美',
  'Robin Nico': '妮可·罗宾',
  'Boa Hancock': '波雅·汉库克',
  'Rukia Kuchiki': '朽木露琪亚',
  'Orihime Inoue': '井上织姬',
  'Yoruichi Shihouin': '四枫院夜一',
  'Erza Scarlet': '艾露莎·舒卡勒托',
  'Lucy Heartfilia': '露西·哈特菲利亚',
  'Mirajane Strauss': '米拉杰·斯特劳斯',
  'Juvia Lockser': '茱比亚·洛克沙',
  'Holo': '赫萝',
  'Taiga Aisaka': '逢坂大河',
  'Ami Kawashima': '川岛亚美',
  'Minori Kushieda': '栉枝实乃梨',
  'Yui Hirasawa': '平泽唯',
  'Mio Akiyama': '秋山澪',
  'Ritsu Tainaka': '田井中律',
  'Tsumugi Kotobuki': '琴吹䌷',
  'Azusa Nakano': '中野梓',
  'Haruhi Suzumiya': '凉宫春日',
  'Yuki Nagato': '长门有希',
  'Mikuru Asahina': '朝比奈实玖瑠',
  'Hinata Kawamoto': '川本日向',
  'Yui Yuigahama': '由比滨结衣',
  'Yukino Yukinoshita': '雪之下雪乃',
  'Iroha Isshiki': '一色彩羽',
  'Shouko Nishimiya': '西宫硝子',
  'Kanna Kamui': '康娜·卡姆依',
  'Tohru': '托尔',
  'Rikka Takanashi': '小鸟游六花',
  'Shinka Nibutani': '丹生谷森夏',
  'Sanae Dekomori': '凸守早苗',
  'Umaru Doma': '土间埋',
  'Chitoge Kirisaki': '桐崎千棘',
  'Kosaki Onodera': '小野寺小咲',
  'Marika Tachibana': '橘万里花',
  'Nico Yazawa': '矢泽妮可',
  'Maki Nishikino': '西木野真姬',
  'Honoka Kousaka': '高坂穗乃果',
  'Eli Ayase': '绚濑绘里',
  'Nozomi Tojo': '东条希',
  'Kotori Minami': '南小鸟',
  'Umi Sonoda': '园田海未',
  'Rin Hoshizora': '星空凛',
  'Hanayo Koizumi': '小泉花阳',
  'Chika Takami': '高海千歌',
  'You Watanabe': '渡边曜',
  'Riko Sakurauchi': '樱内梨子',
  'Ruby Kurosawa': '黑泽露比',
  'Dia Kurosawa': '黑泽黛雅',
  'Yoshiko Tsushima': '津岛善子',
  'Mari Ohara': '小原鞠莉',
  'Kanade Tachibana': '立华奏',
  'Yuri Nakamura': '仲村由理',
  'Isla': '艾拉',
  'Ai Hayasaka': '早坂爱',
  'Chika Fujiwara': '藤原千花',
  'Miko Iino': '伊井野弥子',
  'Shiro': '白',
  'Stephanie Dola': '史蒂芬妮·多拉',
  'Jibril': '吉普莉尔',
  'Lalatina Ford Dustiness': '拉拉蒂娜·福特·达斯特尼斯',
  'Wiz': '维兹',
  'Eris': '厄里斯',
  'Yunyun': '悠悠',
  'Raphtalia': '拉芙塔莉雅',
  'Filo': '菲洛',
  'Roxy Migurdia': '洛琪希·米格路迪亚',
  'Eris Boreas Greyrat': '艾莉丝·伯雷亚斯·格雷拉特',
  'Sylphiette': '希露菲叶特',
  'Ghislaine Dedoldia': '基列奴·泰德路迪亚',
  'Maka Albarn': '玛嘉·阿尔邦',
  'Tsubaki Nakatsukasa': '中务椿',
  'Maka': '玛嘉',
  'Erina Nakiri': '薙切绘里奈',
  'Megumi Tadokoro': '田所惠',
  'Alice Nakiri': '薙切爱丽丝',
  'Hisako Arato': '新户绯沙子',
  'Ikumi Mito': '水户郁魅',
  'Madoka Kaname': '鹿目圆',
  'Homura Akemi': '晓美焰',
  'Mami Tomoe': '巴麻美',
  'Sayaka Miki': '美树沙耶香',
  'Kyoko Sakura': '佐仓杏子',
  'Nagisa Momoe': '百江渚',
  'Hitagi Senjougahara': '战场原黑仪',
  'Shinobu Oshino': '忍野忍',
  'Tsubasa Hanekawa': '羽川翼',
  'Suruga Kanbaru': '神原骏河',
  'Nadeko Sengoku': '千石抚子',
  'Karen Araragi': '阿良良木火怜',
  'Tsukihi Araragi': '阿良良木月火',
  'Yotsugi Ononoki': '斧乃木余接',
  'Sodachi Oikura': '老仓育',
  'Rei Ayanami': '绫波丽',
  'Asuka Langley Souryuu': '明日香',
  'Misato Katsuragi': '葛城美里',
  'Ritsuko Akagi': '赤木律子',
  'Mari Makinami Illustrious': '真希波·玛丽·伊兰崔亚斯',
  'Faye Valentine': '菲·瓦伦丁',
  'Motoko Kusanagi': '草薙素子',
  'Celty Sturluson': '塞尔提·史特路尔森',
  'Kagome Higurashi': '日暮戈薇',
  'Sango': '珊瑚',
  'Kikyo': '桔梗',
  'Winry Rockbell': '温莉·洛克贝尔',
  'Riza Hawkeye': '莉莎·霍克艾',
  'Lust': '拉斯特',
  'Olivier Mira Armstrong': '奥利维亚·米拉·阿姆斯特朗',
  'Lan Fan': '张梅',
  'Tomoyo Sakagami': '坂上智代',
  'Nagisa Furukawa': '古河渚',
  'Kyou Fujibayashi': '藤林杏',
  'Kotomi Ichinose': '一之濑琴美',
  'Fuko Ibuki': '伊吹风子',
  'Ushio Okazaki': '冈崎汐',
  'Yuki Takeya': '丈枪由纪',
  'Kurumi Ebisuzawa': '惠比泽胡桃',
  'Megu-nee': '慈姐',
  'Yuu Koito': '小糸侑',
  'Touko Nanami': '七海灯子',
  'Sayaka Saeki': '佐伯沙弥香',
  'Sakuta Azusagawa': '梓川咲太',
  'Shouko Makinohara': '牧之原翔子',
  'Kaede Azusagawa': '梓川枫',
  'Rio Futaba': '双叶理央',
  'Nodoka Toyohama': '丰浜和花',
  'Tomoe Koga': '古贺朋绘',
  'Chizuru Ichinose': '水原千鹤',
  'Mami Nanami': '七海麻美',
  'Ruka Sarashina': '更科瑠夏',
  'Sumi Sakurasawa': '樱泽墨',
  'Senjougahara': '战场原',
  'Hitagi': '黑仪',
  'Chiyo Sakura': '佐仓千代',
  'Yuuko Aioi': '相生祐子',
  'Mio Naganohara': '长野原美绪',
  'Mai Minakami': '水上麻衣',
  'Nano Shinonome': '东云名乃',
  'Hakase': '博士',
  'Sawako Sekijou': '关城纱和子',
  'Victorique de Blois': '维多利加·德·布洛瓦',
  'Kazusa Touma': '冬马和纱',
  'Setsuna Ogiso': '小木曾雪菜',
  'Mashiro Shiina': '椎名真白',
  'Nanami Aoyama': '青山七海',
  'Misaki Kamiigusa': '上井草美咲',
  'Ryuuko Matoi': '缠流子',
  'Satsuki Kiryuuin': '鬼龙院皐月',
  'Mako Mankanshoku': '满舰饰真子',
  'Nonon Jakuzure': '蛇崩乃音',
  'Lain Iwakura': '岩仓玲音',
  'Hinata Miyake': '三宅日向',
  'Teresa': '泰蕾莎',
  'Clare': '克蕾雅',
  'Galko': '辣妹子',
  'Otako': '宅子',
  'Ojyo': '大小姐',
  'Morgiana': '摩尔迦娜',
  'Kougyoku Ren': '练红玉',
  'Hinata': '日向(天使)', 
  'Satou Matsuzaka': '松坂砂糖',
  'Shio Koube': '神户盐',
  'Kaede Honjou': '本条枫',
  'Sally': '莎莉',
  'Maple': '梅普露',
  'Nanachi': '娜娜奇',
  'Riko': '莉可',
  'Ozen': '奥森',
  'Phosphophyllite': '磷叶石',
  'Diamond': '钻石',
  'Cinnabar': '辰砂',
  'Bort': '圆粒金刚石',
  'Kumoko': '蜘蛛子',
  'Ariel': '爱丽儿',
  'Sophia Keren': '索菲亚·克莲',
  'Shiraori': '白',
  'Tanya von Degurechaff': '谭雅·提古雷查夫',
  'Viktoriya Ivanovna Serebryakov': '维夏',
  'Esdeath': '艾斯德斯',
  'Akame': '赤瞳',
  'Mine': '玛茵',
  'Sheele': '希尔',
  'Leone': '雷欧奈',
  'Chelsea': '切尔茜',
  'Kurome': '黑瞳',
  'Shinoa Hiiragi': '柊筱娅',
  'Mitsuba Sangou': '三宫三叶',
  'Krul Tepes': '克鲁鲁·采佩西',
  'Miyako Hoshino': '星野宫子',
  'Umaru': '小埋',
  'Ayame Himuro': '冰室菖蒲',
  'Komichi Akebi': '明日小路',
  'Ryou Yamada': '山田凉',
  'Bocchi': '后藤独',
  'Nijika Ijichi': '伊地知虹夏',
  'Kita Ikuyo': '喜多郁代',
  'Hitori Gotou': '后藤一里',
  'Ai Hoshino': '星野爱',
  'Ruby Hoshino': '星野瑠美衣',
  'Kana Arima': '有马加奈',
  'Akane Kurokawa': '黑川茜',
  'MEM': 'MEM啾',
  'Anzu Hoshino': '星野杏',
  'Takina Inoue': '井之上泷奈',
  'Chisato Nishikigi': '锦木千束',
  'Kurumi': '胡桃',
  'Mizuki Nakahara': '中原瑞希',
  'Momo Chiyoda': '千代田桃',
  'Rei': '绫波',
  'Pieck Finger': '皮克',
  'Annie Leonhart': '亚妮·雷恩哈特',
  'Sasha Blouse': '萨莎·布劳斯',
  'Historia Reiss': '希斯特利亚·雷斯',
  'Hange Zoe': '韩吉·佐伊',
  'Ymir': '尤米尔',
  'Petra Ral': '佩特拉·拉尔',
  'Albedo': '雅儿贝德',
  'Shalltear Bloodfallen': '夏提雅·布拉德弗伦',
  'Aura Bella Fiora': '亚乌拉·贝拉·菲欧拉',
  'Mare Bello Fiore': '马雷·贝罗·菲欧雷',
  'Demiurge': '迪米乌哥斯', 
  'Narberal Gamma': '娜贝拉尔·伽玛',
  'Lupusregina Beta': '露普斯蕾琪娜·贝塔',
  'Clementine': '克莱门汀',
  'Entoma Vasilissa Zeta': '安多玛',
  'Solution Epsilon': '索留香·艾普西隆',
  'Yuri Alpha': '由莉·阿尔法',
  'Shuna': '朱菜',
  'Shion': '紫苑',
  'Milim Nava': '米莉姆·纳瓦',
  'Revy': '莱薇',
  'Balalaika': '巴拉莱卡',
  'Eda': '艾达',
  'Shenhua': '申华',
  'Roberta': '罗贝尔特',
  'Panty Anarchy': '潘蒂',
  'Stocking Anarchy': '丝多金',
  'Eureka': '优莱卡',
  'Anemone': '银莲花',
  'Echidna': '艾姬多娜',
  'Beatrice': '碧翠丝',
  'Satella': '莎缇拉',
  'Minerva': '米涅瓦',
  'Carmilla': '卡蜜拉',
  'Sekhmet': '塞赫麦特',
  'Daphne': '达芙妮',
  'Typhon': '缇丰',
  'KonoSuba': '为美好的世界献上祝福',
  'Petelgeuse Romaneeconti': '培提尔其乌斯',
  'Regulus Corneas': '雷古勒斯',
  'Sirius': '西里乌斯',
  'Capella Emerada Lugunica': '卡佩拉',
  'Theresia van Astrea': '特蕾西亚',
  'Frederica Baumann': '芙蕾德莉卡',
  'Petra Leyte': '佩特拉',
  'Felt': '菲鲁特',
  'Crusch Karsten': '库珥修·卡尔斯腾',
  'Priscilla Barielle': '普莉希拉·跋利耶尔',
  'Anastasia Hoshin': '阿纳斯塔西娅·霍星',
  'Louis Arneb': '露伊',
  'Rachel Gardner': '瑞秋',
  'Ray': '雷',
  'Zack': '札克',
  'Cathy': '凯西',
  'Miki Makimura': '牧村美树',
  'Vivy': '薇薇',
  'Grace': '葛蕾丝',
  'Ophelia': '奥菲莉亚',
  'Elizabeth': '伊丽莎白',
  'Shirakami Fubuki': '白上吹雪',
  'Natsuiro Matsuri': '夏色祭',
  'Minato Aqua': '凑阿库娅',
  'Yuzuki Choco': '癒月巧可',
  'Ookami Mio': '大神澪',
  'Nekomata Okayu': '猫又小粥',
  'Inugami Korone': '戌神沁音',
  'Nakiri Ayame': '百鬼绫目',
  'Murasaki Shion': '紫咲诗音',
  'Houshou Marine': '宝钟玛琳',
  'Usada Pekora': '兔田佩克拉',
  'Uruha Rushia': '润羽露西娅',
  'Shiranui Flare': '不知火芙蕾雅',
  'Shirogane Noel': '白银诺艾尔',
  'Amane Kanata': '天音彼方',
  'Tokoyami Towa': '常暗永远',
  'Himemori Luna': '姬森璐娜',
  'Kiryu Coco': '桐生可可',
  'Akai Haato': '赤井心',
  'Sakura Miko': '樱巫女',
  'Tsunomaki Watame': '角卷绵芽',
  'Ike Eveland': '艾克·艾弗兰德',
  'Kureiji Ollie': '克蕾西·奥莉',
  'Momosuzu Nene': '桃铃音音',
  'Yuki Suou': '周防雪',
  'Hanasato Minori': '花里实乃理',
  'Kiritani Haruka': '桐谷遥',
  'Momoi Airi': '桃井爱莉',
  'Hinomori Shizuku': '日野森雫',
  'Azusawa Kohane': '小豆泽心羽',
  'Shiraishi An': '白石杏',
  'Shinonome Akito': '东云彰人',
  'Aki Touya': '青柳冬弥',
  'Hatsune Miku': '初音未来',
  'Kagamine Rin': '镜音铃',
  'Kagamine Len': '镜音连',
  'Megurine Luka': '巡音流歌',
  'MEIKO': 'MEIKO',
  'KAITO': 'KAITO',
  'Shimamura Hougetsu': '岛村抱月',
  'Adachi': '安达樱',
  'Vanilla': '香草',
  'Chocola': '巧克力',
  'Maple Nekopara': '枫',
  'Cinnamon': '肉桂',
  'Azuki': '红豆',
  'Coconut': '椰子',
  'Miko': '神子',
  'Reimu': '灵梦',
  'Kyouko Hori': '堀京子',
  'Shima': '志摩',
  'Misuzu Gundo': '郡堂美铃',
  'Kagura': '神乐',
  'Sakata Gintoki': '坂田银时',
  'Tsukuyo': '月咏',
  'Nobume Imai': '今井信女',
  'Tae Shimura': '志村妙',
  'Saya Takagi': '高城沙耶',
  'Sisters': '姐姐大人',
  'Yuki': '小雪',
  'Miyuki Takara': '宝美雪',
  'Konata Izumi': '泉此方',
  'Kagami Hiiragi': '柊镜',
  'Tsukasa Hiiragi': '柊司',
  'Miyuki Takara': '高良美幸',
  'Sawako Yamanaka': '山中佐和子',
  'Nodoka Manabe': '真锅和',
  'Ui Hirasawa': '平泽忧',
  'Jun Suzuki': '铃木纯',
  'Sumire Saito': '齐藤堇',
  'Mugi': '䌷',
  'Himeko Inaba': '稻叶姬子',
  'Iori Nagase': '永濑伊织',
  'Yui Kiriyama': '桐山唯',
  'Yoshifumi Aoki': '青木义文',
  'Yuuichirou': '小鸟游修一',
  'Kaoru Tsunashi': '常木香',
  'Satou': '佐藤',
  'Yoshida': '吉田',
  'Sora': '空',
  'Shuvi Dola': '休比·多拉',
  'Akeno Himejima': '姬岛朱乃',
  'Rias Gremory': '莉亚丝·吉蒙里',
  'Koneko Toujou': '塔城小猫',
  'Asia Argento': '爱西亚·阿尔杰特',
  'Xenovia Quarta': '杰诺瓦',
  'Irina Shidou': '紫藤伊莉娜',
  'Rossweisse': '罗丝薇瑟',
  'Kuroka': '黑歌',
  'Grayfia Lucifuge': '葛瑞菲雅',
  'Aika Kiryuu': '桐生蓝华',
  'Serafall Leviathan': '塞拉芙尔·利维坦',
  'Isuzu Sento': '千斗五十铃',
  'Latifa Fleuranza': '拉提法·弗鲁兰萨',
  'Wendy Marvell': '温蒂·玛贝尔',
  'Cana Alberona': '卡娜·阿尔贝罗纳',
  'Levy McGarden': '蕾比·马克加登',
  'Aries': '阿莉耶斯',
  'Meredy': '梅尔蒂',
  'Ultear Milkovich': '乌鲁蒂亚',
  'Mavis Vermillion': '梅比斯·维维亚米利欧',
  'Sherria Blendy': '雪莉娅·布兰蒂',
  'Dimaria Yesta': '蒂玛利亚',
  'Eileen Belserion': '艾琳·贝尔赛利翁',
  'Brandish': '布兰缇什',
  'Nico Robin': '妮可·罗宾',
  'Violet Evergarden (Auto Memory Doll)': '薇尔莉特',
  'Delta': '德尔塔',
  'Zeta': '泽塔',
  'Epsilon': '艾普西隆',
  'Alpha': '阿尔法',
  'Beta': '贝塔',
  'Gamma': '伽玛',
  'Eta': '艾塔',
  'Bocchi (Hitori Gotou)': '后藤独',
  'Rei Suzumiya': '凉宫',
};

// ═══ 作品名中译映射 ═══
const sourceMap = {
  'Re:Zero kara Hajimeru Isekai Seikatsu': 'Re:从零开始的异世界生活',
  'Shingeki no Kyojin': '进击的巨人',
  'Steins;Gate': '命运石之门',
  'Chainsaw Man': '电锯人',
  'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai': '青春猪头少年不会梦到兔女郎学姐',
  'Sousou no Frieren': '葬送的芙莉莲',
  'Kusuriya no Hitorigoto': '药屋少女的呢喃',
  'Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen': '辉夜大小姐想让我告白',
  'Violet Evergarden': '紫罗兰永恒花园',
  'Sword Art Online': '刀剑神域',
  'Kimetsu no Yaiba': '鬼灭之刃',
  'Demon Slayer: Kimetsu no Yaiba': '鬼灭之刃',
  'Fate/stay night': 'Fate/stay night',
  'Fate/Zero': 'Fate/Zero',
  'Fate/Grand Order': 'Fate/Grand Order',
  'Kono Subarashii Sekai ni Shukufuku wo!': '为美好的世界献上祝福',
  'Kobayashi-san Chi no Maidragon': '小林家的龙女仆',
  'Boku no Hero Academia': '我的英雄学院',
  'My Hero Academia': '我的英雄学院',
  'One Punch Man': '一拳超人',
  'Mob Psycho 100': '灵能百分百',
  'Toradora!': '龙与虎',
  'Clannad': 'CLANNAD',
  'Clannad: After Story': 'CLANNAD ～AFTER STORY～',
  'Angel Beats!': 'Angel Beats!',
  'Charlotte': 'Charlotte',
  'Hyouka': '冰菓',
  'Hibike! Euphonium': '吹响吧！上低音号',
  'K-ON!': '轻音少女',
  'K-On!': '轻音少女',
  'Suzumiya Haruhi no Yuuutsu': '凉宫春日的忧郁',
  'The Melancholy of Haruhi Suzumiya': '凉宫春日的忧郁',
  'Lucky Star': '幸运星',
  'Nichijou': '日常',
  'Kokoro Connect': '心灵链环',
  'Hataraku Maou-sama!': '打工吧！魔王大人',
  'No Game No Life': '游戏人生',
  'Overlord': 'OVERLORD',
  'Tensei Shitara Slime Datta Ken': '关于我转生变成史莱姆这档事',
  'That Time I Got Reincarnated as a Slime': '关于我转生变成史莱姆这档事',
  'Mushoku Tensei: Isekai Ittara Honki Dasu': '无职转生',
  'Youjo Senki': '幼女战记',
  'Saga of Tanya the Evil': '幼女战记',
  'Tate no Yuusha no Nariagari': '盾之勇者成名录',
  'The Rising of the Shield Hero': '盾之勇者成名录',
  'Bungou Stray Dogs': '文豪野犬',
  'Noragami': '野良神',
  'Akame ga Kill!': '斩·赤红之瞳',
  'Kill la Kill': '斩服少女',
  'Darling in the FranXX': 'DARLING in the FRANXX',
  'Neon Genesis Evangelion': '新世纪福音战士',
  'Cowboy Bebop': '星际牛仔',
  'Fullmetal Alchemist: Brotherhood': '钢之炼金术师FA',
  'Fullmetal Alchemist': '钢之炼金术师',
  'Code Geass: Hangyaku no Lelouch': '叛逆的鲁路修',
  'Code Geass': '叛逆的鲁路修',
  'Death Note': '死亡笔记',
  'Tokyo Ghoul': '东京喰种',
  'Tokyo Ghoul √A': '东京喰种√A',
  'Psycho-Pass': '心理测量者',
  'Psycho Pass': '心理测量者',
  'Ghost in the Shell: Stand Alone Complex': '攻壳机动队 S.A.C.',
  'Serial Experiments Lain': '玲音',
  'Elfen Lied': '妖精的旋律',
  'Higurashi no Naku Koro ni': '寒蝉鸣泣之时',
  'Another': '替身',
  'Mirai Nikki': '未来日记',
  'The Future Diary': '未来日记',
  'Shiki': '尸鬼',
  'Monogatari Series': '物语系列',
  'Bakemonogatari': '化物语',
  'Nisemonogatari': '伪物语',
  'Nekomonogatari: Kuro': '猫物语(黑)',
  'Monogatari Series: Second Season': '物语系列 第二季',
  'Owarimonogatari': '终物语',
  'Love Live! School Idol Project': 'Love Live!',
  'Love Live!': 'Love Live!',
  'Love Live! Sunshine!!': 'Love Live! Sunshine!!',
  'Love Live! Superstar!!': 'Love Live! Superstar!!',
  'Bocchi the Rock!': '孤独摇滚！',
  'Lycoris Recoil': '莉可丽丝',
  'Spy x Family': '间谍过家家',
  'Oshi no Ko': '我推的孩子',
  'Kaguya-sama: Love is War': '辉夜大小姐想让我告白',
  'Yahari Ore no Seishun Love Comedy wa Machigatteiru.': '我的青春恋爱物语果然有问题。',
  'Oregairu': '我的青春恋爱物语果然有问题。',
  'Saenai Heroine no Sodatekata': '路人女主的养成方法',
  'Sakurasou no Pet na Kanojo': '樱花庄的宠物女孩',
  'Guilty Crown': '罪恶王冠',
  'Angel Beats': 'Angel Beats!',
  'Your Lie in April': '四月是你的谎言',
  'Shigatsu wa Kimi no Uso': '四月是你的谎言',
  'Anohana: The Flower We Saw That Day': '我们仍未知道那天所看见的花的名字',
  'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.': '未闻花名',
  'Kimi no Na wa.': '你的名字。',
  'Your Name.': '你的名字。',
  'Koe no Katachi': '声之形',
  'A Silent Voice': '声之形',
  '5-toubun no Hanayome': '五等分的新娘',
  'The Quintessential Quintuplets': '五等分的新娘',
  'Gotoubun no Hanayome': '五等分的新娘',
  'Boku wa Tomodachi ga Sukunai': '我的朋友很少',
  'Haganai': '我的朋友很少',
  'Date A Live': '约会大作战',
  'Mahou Shoujo Madoka Magica': '魔法少女小圆',
  'Puella Magi Madoka Magica': '魔法少女小圆',
  'Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation': '弹丸论破',
  'Danganronpa': '弹丸论破',
  'Shokugeki no Souma': '食戟之灵',
  'Food Wars': '食戟之灵',
  'Toaru Kagaku no Railgun': '某科学的超电磁炮',
  'Toaru Majutsu no Index': '魔法禁书目录',
  'A Certain Scientific Railgun': '某科学的超电磁炮',
  'A Certain Magical Index': '魔法禁书目录',
  'Gurren Lagann': '天元突破红莲螺岩',
  'Tengen Toppa Gurren Lagann': '天元突破红莲螺岩',
  'Black Lagoon': '黑礁',
  'Hellsing Ultimate': '皇家国教骑士团',
  'Hellsing': '皇家国教骑士团',
  'Jujutsu Kaisen': '咒术回战',
  'Komi-san wa, Comyushou desu.': '古见同学有交流障碍症',
  'Komi Can\'t Communicate': '古见同学有交流障碍症',
  'Sono Bisque Doll wa Koi wo Suru': '更衣人偶坠入爱河',
  'My Dress-Up Darling': '更衣人偶坠入爱河',
  'Horimiya': '堀与宫村',
  'Hori-san to Miyamura-kun': '堀与宫村',
  'Tonikaku Kawaii': '总之就是非常可爱',
  'Karakai Jouzu no Takagi-san': '擅长捉弄的高木同学',
  'Uzaki-chan wa Asobitai!': '宇崎酱想要玩耍！',
  'Ijiranaide, Nagatoro-san': '不要欺负我，长瀞同学',
  'Kanojo, Okarishimasu': '租借女友',
  'Rent-a-Girlfriend': '租借女友',
  'Kanojo mo Kanojo': '她也是女友',
  'Fuufu Ijou, Koibito Miman.': '夫妇以上，恋人未满',
  'Yofukashi no Uta': '夜曲',
  'Call of the Night': '夜曲',
  'Shadows House': '影宅',
  'Made in Abyss': '来自深渊',
  'Houseki no Kuni': '宝石之国',
  'Land of the Lustrous': '宝石之国',
  'Vivy: Fluorite Eye\'s Song': 'Vivy -Fluorite Eye\'s Song-',
  '86': '86-不存在的战区-',
  'Cyberpunk: Edgerunners': '赛博朋克：边缘行者',
  'Edgerunners': '赛博朋克：边缘行者',
  'Vinland Saga': '海盗战记',
  'Grand Blue': '碧蓝之海',
  'Grand Blue Dreaming': '碧蓝之海',
  'Asobi Asobase': '游戏三人娘',
  'Gintama': '银魂',
  'Gekkan Shoujo Nozaki-kun': '月刊少女野崎君',
  'Monthly Girls\' Nozaki-kun': '月刊少女野崎君',
  'Jahy-sama wa Kujikenai!': '贾希大人不气馁！',
  'Hinamatsuri': '超能力女儿',
  'Gabriel DropOut': '珈百璃的堕落',
  'Blend S': '调教咖啡厅',
  'New Game!': 'NEW GAME!',
  'Gochuumon wa Usagi Desu ka?': '请问您今天要来点兔子吗？',
  'Is the Order a Rabbit?': '请问您今天要来点兔子吗？',
  'Fruits Basket': '水果篮子',
  'Fruits Basket (2019)': '水果篮子 (2019)',
  'Nana': 'NANA',
  'Paradise Kiss': '天堂之吻',
  'Suki-tte Ii na yo.': '只要你说你爱我',
  'Say "I love you"': '只要你说你爱我',
  'Ao Haru Ride': '青春之旅',
  'Blue Spring Ride': '青春之旅',
  'Ookami Shoujo to Kuro Ouji': '狼少女与黑王子',
  'Wolf Girl and Black Prince': '狼少女与黑王子',
  'Orange': 'orange',
  'Kuzu no Honkai': '人渣的本愿',
  'Scum\'s Wish': '人渣的本愿',
  'Wotaku ni Koi wa Muzukashii': '宅男腐女恋爱真难',
  'Danna ga Nani wo Itteiru ka Wakaranai Ken': '我不明了丈夫在说什么',
  'Shoujo Shuumatsu Ryokou': '少女终末旅行',
  'Girls\' Last Tour': '少女终末旅行',
  'Yuru Camp': '摇曳露营',
  'Laid-Back Camp': '摇曳露营',
  'Non Non Biyori': '悠哉日常大王',
  'Barakamon': '元气囝仔',
  'Poco\'s Udon World': '乌冬面之国的金色毛球',
  'Amaama to Inazuma': '甜蜜稻妻',
  'Sweetness and Lightning': '甜蜜稻妻',
  'Usagi Drop': '白兔糖',
  'Bunny Drop': '白兔糖',
  'Chuunibyou demo Koi ga Shitai!': '中二病也要谈恋爱！',
  'Love, Chunibyo & Other Delusions!': '中二病也要谈恋爱！',
  'Tamako Market': '玉子市场',
  'Tamako Love Story': '玉子爱情故事',
  'Hyouka (The series)': '冰菓',
  'Kyoukai no Kanata': '境界的彼方',
  'Beyond the Boundary': '境界的彼方',
  'Kobayashi-san Chi no Maid Dragon': '小林家的龙女仆',
  'Miss Kobayashi\'s Dragon Maid': '小林家的龙女仆',
  'Gakkou Gurashi!': '学园孤岛',
  'School-Live!': '学园孤岛',
  'Mahoutsukai no Yome': '魔法使之嫁',
  'The Ancient Magus\' Bride': '魔法使之嫁',
  'FAIRY TAIL': '妖精的尾巴',
  'Fairy Tail': '妖精的尾巴',
  'ONE PIECE': '海贼王',
  'One Piece': '海贼王',
  'NARUTO': '火影忍者',
  'Naruto': '火影忍者',
  'Naruto: Shippuuden': '火影忍者疾风传',
  'Bleach': '死神',
  'Dragon Ball': '龙珠',
  'Dragon Ball Z': '龙珠Z',
  'Dragon Ball Super': '龙珠超',
  'HUNTER×HUNTER': '全职猎人',
  'Hunter x Hunter': '全职猎人',
  'Yu Yu Hakusho': '幽游白书',
  'Rurouni Kenshin': '浪客剑心',
  'Inuyasha': '犬夜叉',
  'Ranma ½': '乱马1/2',
  'Sailor Moon': '美少女战士',
  'Bishoujo Senshi Sailor Moon': '美少女战士',
  'Cardcaptor Sakura': '魔卡少女樱',
  'Chobits': '人形电脑天使心',
  'Tsubasa Chronicle': '翼·年代记',
  'xxxHOLiC': 'xxxHOLiC',
  'Kobato.': '小鸠',
  'Blood+': 'Blood+',
  'Ergo Proxy': '死亡代理人',
  'Texhnolyze': '特工次时代',
  'Monster': 'MONSTER',
  'Gantz': '杀戮都市',
  'Berserk': '剑风传奇',
  'Claymore': '大剑',
  'Hokuto no Ken': '北斗神拳',
  'JoJo no Kimyou na Bouken': 'JOJO的奇妙冒险',
  'JoJo\'s Bizarre Adventure': 'JOJO的奇妙冒险',
  'Black Butler': '黑执事',
  'Kuroshitsuji': '黑执事',
  'Pandora Hearts': '潘朵拉之心',
  'D.Gray-man': '驱魔少年',
  'Soul Eater': '噬魂师',
  'Blue Exorcist': '青之驱魔师',
  'Ao no Exorcist': '青之驱魔师',
  'Magi: The Labyrinth of Magic': '魔笛MAGI',
  'Magi': '魔笛MAGI',
  'Akatsuki no Yona': '拂晓的尤娜',
  'Yona of the Dawn': '拂晓的尤娜',
  'Snow White with the Red Hair': '赤发白雪姬',
  'Akagami no Shirayukihime': '赤发白雪姬',
  'Kaichou wa Maid-sama!': '会长是女仆大人！',
  'Maid Sama!': '会长是女仆大人！',
  'Special A': 'SA特优生',
  'Lovely Complex': '恋爱情结',
  'Itazura na Kiss': '淘气小亲亲',
  'Ouran Koukou Host Club': '樱兰高校男公关部',
  'Ouran High School Host Club': '樱兰高校男公关部',
  'Vampire Knight': '吸血鬼骑士',
  'Diabolik Lovers': '魔鬼爱人',
  'Amnesia': '失忆症',
  'Brothers Conflict': '兄弟战争',
  'Uta no Prince-sama': '歌之王子殿下',
  'Free!': 'Free!',
  'Haikyuu!!': '排球少年！！',
  'Kuroko no Basket': '黑子的篮球',
  'Blue Lock': '蓝色监狱',
  'Yuri!!! on ICE': '冰上的尤里',
  'Initial D': '头文字D',
  'MF Ghost': 'MF GHOST',
  'Wangan Midnight': '湾岸Midnight',
  'Slam Dunk': '灌篮高手',
  'Captain Tsubasa': '足球小将',
  'Eyeshield 21': '光速跑者21号',
  'Diamond no Ace': '钻石王牌',
  'Major': '棒球大联盟',
  'Yowamushi Pedal': '飙速宅男',
  'Girls und Panzer': '少女与战车',
  'Kantai Collection': '舰队Collection',
  'KanColle': '舰队Collection',
  'Azur Lane': '碧蓝航线',
  'Arknights': '明日方舟',
  'Genshin Impact': '原神',
  'Honkai: Star Rail': '崩坏：星穹铁道',
  'Honkai Impact 3rd': '崩坏3',
  'Fate/Grand Order Absolute Demonic Front: Babylonia': 'Fate/Grand Order 绝对魔兽战线巴比伦尼亚',
  'Princess Connect! Re:Dive': '公主连结Re:Dive',
  'Uma Musume Pretty Derby': '赛马娘 Pretty Derby',
  'THE IDOLM@STER': '偶像大师',
  'THE iDOLM@STER': '偶像大师',
  'THE IDOLM@STER CINDERELLA GIRLS': '偶像大师灰姑娘女孩',
  'THE IDOLM@STER SHINY COLORS': '偶像大师闪耀色彩',
  'Zombie Land Saga': '佐贺偶像是传奇',
  'Idoly Pride': 'IDOLY PRIDE',
  'Selection Project': 'SELECTION PROJECT',
  '22/7': '22/7',
  'Wake Up, Girls!': 'Wake Up, Girls!',
  'Aikatsu!': '偶像活动！',
  'Pretty Rhythm': '星光少女',
  'PriPara': 'PriPara',
  'Kiratto Pri☆Chan': '闪亮Q☆CHAN',
  'BanG Dream!': 'BanG Dream!',
  'D4DJ First Mix': 'D4DJ First Mix',
  'Project Sekai': '世界计划 彩色舞台',
  'Hatsune MIX': '初音MIX',
  'VOCALOID': 'VOCALOID',
  'Nekopara': '巧克力与香子兰',
  'NEKOPARA': '巧克力与香子兰',
  'Hyperdimension Neptunia': '超次元游戏海王星',
  'Senran Kagura': '闪乱神乐',
  'Dead or Alive': '死或生',
  'Street Fighter': '街头霸王',
  'Tekken': '铁拳',
  'King of Fighters': '拳皇',
  'Persona 5': '女神异闻录5',
  'Persona 4': '女神异闻录4',
  'Persona 3': '女神异闻录3',
  'Persona 5: The Animation': '女神异闻录5',
  'Persona 4: The Animation': '女神异闻录4',
  'Final Fantasy VII': '最终幻想VII',
  'Final Fantasy X': '最终幻想X',
  'Final Fantasy XIII': '最终幻想XIII',
  'Final Fantasy XV': '最终幻想XV',
  'Nier:Automata': '尼尔：机械纪元',
  'NieR:Automata': '尼尔：机械纪元',
  'NieR': '尼尔',
  'Fire Emblem': '火焰之纹章',
  'Xenoblade Chronicles': '异度之刃',
  'Danganronpa 2': '弹丸论破2',
  'Danganronpa V3': '新弹丸论破V3',
  'Ace Attorney': '逆转裁判',
  'Touhou Project': '东方Project',
  'Shingeki no Kyojin: The Final Season': '进击的巨人 最终季',
  'Bleach: Sennen Kessen-hen': '死神 千年血战篇',
  'Bleach: Thousand-Year Blood War': '死神 千年血战篇',
  'Jujutsu Kaisen 2nd Season': '咒术回战 第二季',
  'Kusuriya no Hitorigoto (2025)': '药屋少女的呢喃',
};

// ═══ 应用翻译 ═══
db.forEach(function(c) {
  if (nameMap[c.name]) c.name = nameMap[c.name];
  if (sourceMap[c.source_anime]) c.source_anime = sourceMap[c.source_anime];
});

// ═══ 25 个东方角色 ═══
const touhouIdBase = 900000;
const touhou = [
  {id:touhouIdBase+1,name:'博丽灵梦',name_native:'博麗霊夢',source_anime:'东方Project',source_type:'GAME',favourites:18000,image:'',description:'博丽神社的巫女，幻想乡的守护者。懒散但实力超群，平时喝茶扫地，异变时第一个出动。口头禅「这是异变啊！」性格大大咧咧，对钱和赛钱格外在意。',tags:{personality:[{id:'genki',level:0.6},{id:'airhead',level:0.5},{id:'mature',level:0.4}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_douki'}],role:[{id:'mage'},{id:'healer'},{id:'wanderer'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'},{id:'tone_battle'}],relationship:[{id:'rel_equal'},{id:'rel_buddy'}],communication:[{id:'comm_frank'}],values:[{id:'val_justice'},{id:'val_independent'},{id:'val_freedom'}],hair:[{id:'hair_black'},{id:'hair_long'}],body:[{id:'body_average'},{id:'body_slim'}],eye:[{id:'eye_brown'}],wardrobe:[{id:'cloth_kimono'}],expression:[{id:'expr_bright'},{id:'expr_lazy'}],special:[{id:'sp_ahoge'}]}},
  {id:touhouIdBase+2,name:'雾雨魔理沙',name_native:'霧雨魔理沙',source_anime:'东方Project',source_type:'GAME',favourites:17500,image:'',description:'普通的魔法使。住在魔法之森，擅长光和热的魔法。性格元气开朗，自称「幻想乡最强」。虽然经常借东西不还，但关键时刻意外可靠。名言：「弹幕就是火力だぜ！」',tags:{personality:[{id:'genki',level:0.9},{id:'comedic',level:0.6},{id:'chuunibyou',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_douki'}],role:[{id:'mage'},{id:'wanderer'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'},{id:'tone_battle'}],relationship:[{id:'rel_equal'},{id:'rel_buddy'}],communication:[{id:'comm_frank'}],values:[{id:'val_freedom'},{id:'val_independent'}],hair:[{id:'hair_blonde'},{id:'hair_long'}],body:[{id:'body_average'},{id:'body_petite'}],eye:[{id:'eye_gold'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_bright'}],special:[{id:'sp_ahoge'}]}},
  {id:touhouIdBase+3,name:'十六夜咲夜',name_native:'十六夜咲夜',source_anime:'东方Project',source_type:'GAME',favourites:16500,image:'',description:'红魔馆的女仆长，完全潇洒的从者。精通时间操控能力，战斗时无数飞刀精准切割。对大小姐蕾米莉亚绝对忠诚，家务万能。银发短发的完美女仆，优雅且致命。',tags:{personality:[{id:'kuudere',level:0.7},{id:'mature',level:0.6},{id:'mysterious',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_senpai'}],role:[{id:'maid'},{id:'assassin'}],series_tone:[{id:'tone_scifi'},{id:'tone_battle'},{id:'tone_dark'}],relationship:[{id:'rel_dependent'},{id:'rel_leader'}],communication:[{id:'comm_reserved'},{id:'comm_rational'}],values:[{id:'val_protective'},{id:'val_justice'}],hair:[{id:'hair_white'},{id:'hair_short'}],body:[{id:'body_tall'},{id:'body_slim'}],eye:[{id:'eye_blue'}],wardrobe:[{id:'cloth_maid'}],expression:[{id:'expr_sharp'}],special:[{id:'sp_maid_headband'}]}},
  {id:touhouIdBase+4,name:'蕾米莉亚·斯卡雷特',name_native:'レミリア・スカーレット',source_anime:'东方Project',source_type:'GAME',favourites:16000,image:'',description:'红魔馆的主人，500岁的吸血鬼大小姐。外表萝莉但威严满满（自称）。操控命运的能力无人能及，性格高傲中带点孩子气。深红洋装和翼型披风是经典标志。',tags:{personality:[{id:'tsundere',level:0.7},{id:'queen',level:0.8},{id:'chuunibyou',level:0.5},{id:'imouto',level:0.4}],age_visual:[{id:'age_v_loli'}],age_aura:[{id:'age_a_senpai'}],age_paradox:[{id:'age_p_legal_loli'}],role:[{id:'noble'},{id:'godly'}],series_tone:[{id:'tone_scifi'},{id:'tone_dark'},{id:'tone_comedy'}],relationship:[{id:'rel_leader'},{id:'rel_dependent'}],communication:[{id:'comm_frank'},{id:'comm_snarky'}],values:[{id:'val_independent'},{id:'val_utilitarian'}],hair:[{id:'hair_blue'},{id:'hair_short'}],body:[{id:'body_petite'},{id:'body_loli_height'}],eye:[{id:'eye_red'}],wardrobe:[{id:'cloth_gothic'},{id:'cloth_elegant'}],expression:[{id:'expr_sharp'},{id:'expr_crazy'}],special:[{id:'sp_vampire_fangs'},{id:'sp_wings'}]}},
  {id:touhouIdBase+5,name:'芙兰朵露·斯卡雷特',name_native:'フランドール・スカーレット',source_anime:'东方Project',source_type:'GAME',favourites:15500,image:'',description:'蕾米莉亚的妹妹，495岁的吸血鬼。被关在地下室近500年的禁忌存在。拥有毁灭一切的能力，但精神状态极不稳定。七彩宝石翅膀是其标志，可爱又危险。',tags:{personality:[{id:'yandere',level:0.9},{id:'airhead',level:0.5},{id:'genki',level:0.6},{id:'imouto',level:0.8}],age_visual:[{id:'age_v_loli'}],age_aura:[{id:'age_a_kouhai'}],age_paradox:[{id:'age_p_legal_loli'}],role:[{id:'godly'},{id:'noble'}],series_tone:[{id:'tone_dark'},{id:'tone_scifi'}],relationship:[{id:'rel_dependent'},{id:'rel_healer'}],communication:[{id:'comm_sweet'},{id:'comm_volatile'}],values:[{id:'val_freedom'},{id:'val_kindness'}],hair:[{id:'hair_blonde'},{id:'hair_short'}],body:[{id:'body_petite'},{id:'body_loli_height'}],eye:[{id:'eye_red'}],wardrobe:[{id:'cloth_gothic'}],expression:[{id:'expr_crazy'},{id:'expr_bright'}],special:[{id:'sp_vampire_fangs'},{id:'sp_wings'}]}},
  {id:touhouIdBase+6,name:'帕秋莉·诺蕾姬',name_native:'パチュリー・ノーレッジ',source_anime:'东方Project',source_type:'GAME',favourites:14000,image:'',description:'红魔馆地下大图书馆的魔女。体弱多病，平时基本不出图书馆门。精通七曜魔法，是幻想乡最博学的魔法使之一。紫发长袍，冷静理性的知识型角色。',tags:{personality:[{id:'kuudere',level:0.8},{id:'no_expression',level:0.5},{id:'mature',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_senpai'}],role:[{id:'mage'},{id:'scientist'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_buddy'},{id:'rel_equal'}],communication:[{id:'comm_silent'},{id:'comm_rational'}],values:[{id:'val_independent'},{id:'val_utilitarian'}],hair:[{id:'hair_purple'},{id:'hair_long'}],body:[{id:'body_slim'},{id:'body_petite'}],eye:[{id:'eye_purple'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_empty'},{id:'expr_lazy'}],special:[]}},
  {id:touhouIdBase+7,name:'爱丽丝·玛格特罗伊德',name_native:'アリス・マーガトロイド',source_anime:'东方Project',source_type:'GAME',favourites:13500,image:'',description:'住在魔法之森的七色人形师。操控人偶的能力出神入化，擅长精密操作和策略布置。金发蓝衣，是东方系列中第一金发傲娇系角色。',tags:{personality:[{id:'tsundere',level:0.7},{id:'mature',level:0.5},{id:'mysterious',level:0.4}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_douki'}],role:[{id:'mage'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_equal'},{id:'rel_leader'}],communication:[{id:'comm_reserved'},{id:'comm_snarky'}],values:[{id:'val_independent'}],hair:[{id:'hair_blonde'},{id:'hair_short'}],body:[{id:'body_average'}],eye:[{id:'eye_blue'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_sharp'}],special:[]}},
  {id:touhouIdBase+8,name:'琪露诺',name_native:'チルノ',source_anime:'东方Project',source_type:'GAME',favourites:13000,image:'',description:'雾之湖的冰之妖精。自称「最强」，是幻想乡最著名的笨蛋⑨。操控冷气的能力其实不弱，但战斗智商堪忧，经常被当教学素材。蓝色冰晶翅膀，天真烂漫。',tags:{personality:[{id:'genki',level:0.9},{id:'airhead',level:1.0},{id:'chuunibyou',level:0.8},{id:'comedic',level:0.8}],age_visual:[{id:'age_v_loli'}],age_aura:[{id:'age_a_kouhai'}],role:[{id:'mage'},{id:'godly'}],series_tone:[{id:'tone_comedy'},{id:'tone_scifi'}],relationship:[{id:'rel_buddy'},{id:'rel_dependent'}],communication:[{id:'comm_frank'},{id:'comm_sweet'}],values:[{id:'val_freedom'},{id:'val_independent'}],hair:[{id:'hair_blue'},{id:'hair_short'}],body:[{id:'body_petite'},{id:'body_loli_height'}],eye:[{id:'eye_blue'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_bright'}],special:[{id:'sp_wings'}]}},
  {id:touhouIdBase+9,name:'魂魄妖梦',name_native:'魂魄妖夢',source_anime:'东方Project',source_type:'GAME',favourites:12500,image:'',description:'白玉楼的庭师，半人半灵的存在。身边漂浮的半灵是自己的一部分。双刀流剑士，性格认真但偏天然直率，经常被幽幽子捉弄。银白短发是标志。',tags:{personality:[{id:'kuudere',level:0.5},{id:'gentle',level:0.6},{id:'airhead',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_kouhai'}],role:[{id:'warrior'},{id:'maid'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_dependent'},{id:'rel_equal'}],communication:[{id:'comm_reserved'},{id:'comm_sweet'}],values:[{id:'val_protective'},{id:'val_justice'}],hair:[{id:'hair_white'},{id:'hair_short'}],body:[{id:'body_slim'}],eye:[{id:'eye_blue'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_gentle'},{id:'expr_lazy'}],special:[]}},
  {id:touhouIdBase+10,name:'西行寺幽幽子',name_native:'西行寺幽々子',source_anime:'东方Project',source_type:'GAME',favourites:12000,image:'',description:'白玉楼的主人，亡灵公主。优雅从容的大小姐外表下，是个料理黑洞级的吃货。操控死亡的能力极其强大，但大部分时间只想吃饭。粉樱和服，笑里藏刀。',tags:{personality:[{id:'mysterious',level:0.7},{id:'fukuro',level:0.7},{id:'gentle',level:0.5},{id:'comedic',level:0.6}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_senpai'}],role:[{id:'noble'},{id:'godly'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_leader'},{id:'rel_equal'}],communication:[{id:'comm_frank'},{id:'comm_snarky'}],values:[{id:'val_freedom'},{id:'val_utilitarian'}],hair:[{id:'hair_red'},{id:'hair_short'}],body:[{id:'body_average'}],eye:[{id:'eye_red'}],wardrobe:[{id:'cloth_kimono'}],expression:[{id:'expr_gentle'},{id:'expr_lazy'}],special:[]}},
  {id:touhouIdBase+11,name:'八云紫',name_native:'八雲紫',source_anime:'东方Project',source_type:'GAME',favourites:11800,image:'',description:'幻想乡最古老的妖怪贤者之一。操控境界的能力近乎法则级，常年沉睡，醒来时操控全局。外表懒散金发美人，实际比谁都聪明。名言「永远十七岁」。',tags:{personality:[{id:'mysterious',level:0.9},{id:'fukuro',level:0.9},{id:'queen',level:0.7},{id:'mature',level:0.8}],age_visual:[{id:'age_v_mature'}],age_aura:[{id:'age_a_senpai'}],age_paradox:[{id:'age_p_loli_baba'}],role:[{id:'godly'},{id:'noble'}],series_tone:[{id:'tone_scifi'},{id:'tone_mystery'}],relationship:[{id:'rel_leader'},{id:'rel_equal'}],communication:[{id:'comm_frank'},{id:'comm_snarky'},{id:'comm_rational'}],values:[{id:'val_utilitarian'},{id:'val_freedom'},{id:'val_independent'}],hair:[{id:'hair_blonde'},{id:'hair_long'}],body:[{id:'body_tall'},{id:'body_average'}],eye:[{id:'eye_purple'}],wardrobe:[{id:'cloth_elegant'}],expression:[{id:'expr_lazy'},{id:'expr_sharp'}],special:[]}},
  {id:touhouIdBase+12,name:'古明地恋',name_native:'古明地こいし',source_anime:'东方Project',source_type:'GAME',favourites:11500,image:'',description:'地灵殿的二小姐，无意识的妖怪。封闭了读心能力，随心所欲地在幻想乡各处潜行。带帽子挡住第三只眼。天真又危险的萝莉角色，无数同人作品的女主角。',tags:{personality:[{id:'airhead',level:0.7},{id:'mysterious',level:0.7},{id:'no_expression',level:0.5},{id:'yandere',level:0.4}],age_visual:[{id:'age_v_loli'}],age_aura:[{id:'age_a_kouhai'}],role:[{id:'godly'},{id:'wanderer'}],series_tone:[{id:'tone_scifi'},{id:'tone_dark'}],relationship:[{id:'rel_equal'},{id:'rel_dependent'}],communication:[{id:'comm_silent'}],values:[{id:'val_freedom'},{id:'val_independent'}],hair:[{id:'hair_green'},{id:'hair_short'}],body:[{id:'body_petite'},{id:'body_loli_height'}],eye:[{id:'eye_purple'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_empty'},{id:'expr_gentle'}],special:[]}},
  {id:touhouIdBase+13,name:'古明地觉',name_native:'古明地さとり',source_anime:'东方Project',source_type:'GAME',favourites:11200,image:'',description:'地灵殿的主人，读心的妖怪。第三只眼能看透一切人心，因此不太擅长社交。粉色短发加睡袍风洋装。对宠物和妹妹非常温柔，是内向型的正经角色。',tags:{personality:[{id:'kuudere',level:0.7},{id:'mature',level:0.5},{id:'gentle',level:0.6}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_douki'}],role:[{id:'noble'},{id:'godly'}],series_tone:[{id:'tone_scifi'},{id:'tone_mystery'}],relationship:[{id:'rel_healer'},{id:'rel_equal'}],communication:[{id:'comm_reserved'},{id:'comm_silent'}],values:[{id:'val_kindness'},{id:'val_protective'}],hair:[{id:'hair_red'},{id:'hair_short'}],body:[{id:'body_average'},{id:'body_petite'}],eye:[{id:'eye_purple'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_gentle'},{id:'expr_lazy'}],special:[]}},
  {id:touhouIdBase+14,name:'铃仙·优昙华院·因幡',name_native:'鈴仙・優曇華院・イナバ',source_anime:'东方Project',source_type:'GAME',favourites:11000,image:'',description:'永远亭的月兔，曾是月球防卫队的士兵。能操控波长，使人产生幻觉或发狂。性格温和但战斗能力不弱，经常被永琳差使。兔耳+紫色短发+红瞳是经典设计。',tags:{personality:[{id:'gentle',level:0.7},{id:'kuudere',level:0.4},{id:'imouto',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_kouhai'}],role:[{id:'warrior'},{id:'mage'},{id:'healer'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_dependent'},{id:'rel_equal'}],communication:[{id:'comm_sweet'},{id:'comm_reserved'}],values:[{id:'val_protective'},{id:'val_kindness'}],hair:[{id:'hair_purple'},{id:'hair_short'}],body:[{id:'body_average'}],eye:[{id:'eye_red'}],wardrobe:[{id:'cloth_uniform'}],expression:[{id:'expr_gentle'}],special:[{id:'sp_nekomimi'}]}},
  {id:touhouIdBase+15,name:'东风谷早苗',name_native:'東風谷早苗',source_anime:'东方Project',source_type:'GAME',favourites:10800,image:'',description:'守矢神社的现人神巫女。从外界来到幻想乡的风祝，操控奇迹的能力。绿发+蛇形发饰，自信满满，认为自己是世界主角。经典口头禅「常识？这里不需要常识」。',tags:{personality:[{id:'genki',level:0.7},{id:'tsundere',level:0.4},{id:'chuunibyou',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_douki'}],role:[{id:'healer'},{id:'mage'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_equal'},{id:'rel_leader'}],communication:[{id:'comm_frank'},{id:'comm_sweet'}],values:[{id:'val_independent'},{id:'val_kindness'}],hair:[{id:'hair_green'},{id:'hair_long'}],body:[{id:'body_average'}],eye:[{id:'eye_green'}],wardrobe:[{id:'cloth_kimono'}],expression:[{id:'expr_bright'}],special:[]}},
  {id:touhouIdBase+16,name:'射命丸文',name_native:'射命丸文',source_anime:'东方Project',source_type:'GAME',favourites:10500,image:'',description:'妖怪之山的鸦天狗记者。幻想乡最速的新闻人，操控风的能力突破天际。黑发短裙+天狗木屐，带着相机到处追新闻，报道内容真假参半。过分热情的媒体人。',tags:{personality:[{id:'genki',level:0.8},{id:'comedic',level:0.7},{id:'mysterious',level:0.4}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_douki'}],role:[{id:'wanderer'},{id:'detective'}],series_tone:[{id:'tone_comedy'},{id:'tone_scifi'}],relationship:[{id:'rel_buddy'},{id:'rel_equal'}],communication:[{id:'comm_frank'},{id:'comm_snarky'}],values:[{id:'val_freedom'},{id:'val_independent'}],hair:[{id:'hair_black'},{id:'hair_short'}],body:[{id:'body_slim'},{id:'body_tall'}],eye:[{id:'eye_brown'}],wardrobe:[{id:'cloth_uniform'}],expression:[{id:'expr_bright'},{id:'expr_sharp'}],special:[{id:'sp_wings'}]}},
  {id:touhouIdBase+17,name:'藤原妹红',name_native:'藤原妹紅',source_anime:'东方Project',source_type:'GAME',favourites:10200,image:'',description:'竹林里的不死之人。服用蓬莱之药后活了1300+年，身体不死。操控火焰的白发少女，每天用打不死的身体硬抗各种攻击。和辉夜是千年的冤家，打架也是日常。',tags:{personality:[{id:'tsundere',level:0.7},{id:'kuudere',level:0.5},{id:'genki',level:0.5},{id:'mature',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_senpai'}],age_paradox:[{id:'age_p_loli_baba'}],role:[{id:'warrior'},{id:'mage'}],series_tone:[{id:'tone_scifi'},{id:'tone_battle'}],relationship:[{id:'rel_equal'},{id:'rel_buddy'}],communication:[{id:'comm_frank'}],values:[{id:'val_freedom'},{id:'val_protective'}],hair:[{id:'hair_white'},{id:'hair_long'}],body:[{id:'body_slim'}],eye:[{id:'eye_red'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_sharp'}],special:[{id:'sp_scar'}]}},
  {id:touhouIdBase+18,name:'蓬莱山辉夜',name_native:'蓬莱山輝夜',source_anime:'东方Project',source_type:'GAME',favourites:10000,image:'',description:'永远亭的公主，月之都的辉夜姬。黑长直+十二单和服的高贵美人。操控永恒与须臾的能力。外表优雅文艺宅女，实际上沉迷游戏和网络，千年资深宅。',tags:{personality:[{id:'fukuro',level:0.6},{id:'gentle',level:0.5},{id:'mature',level:0.5},{id:'mysterious',level:0.6},{id:'queen',level:0.5}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_senpai'}],age_paradox:[{id:'age_p_loli_baba'}],role:[{id:'noble'},{id:'godly'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_buddy'},{id:'rel_equal'}],communication:[{id:'comm_reserved'},{id:'comm_snarky'}],values:[{id:'val_independent'},{id:'val_freedom'}],hair:[{id:'hair_black'},{id:'hair_long'}],body:[{id:'body_average'}],eye:[{id:'eye_brown'}],wardrobe:[{id:'cloth_kimono'},{id:'cloth_elegant'}],expression:[{id:'expr_lazy'},{id:'expr_gentle'}],special:[]}},
  {id:touhouIdBase+19,name:'八意永琳',name_native:'八意永琳',source_anime:'东方Project',source_type:'GAME',favourites:9800,image:'',description:'永远亭的实际管理人，月球来的贤者。精通医药的天才医师，年龄不可考的银发御姐。长弓擅射，战斗时冷静致命。对辉夜忠贞不渝，是幻想乡最全能的存在之一。',tags:{personality:[{id:'mature',level:0.9},{id:'mysterious',level:0.7},{id:'fukuro',level:0.6},{id:'cold',level:0.4}],age_visual:[{id:'age_v_mature'}],age_aura:[{id:'age_a_senpai'}],age_paradox:[{id:'age_p_loli_baba'}],role:[{id:'scientist'},{id:'healer'},{id:'godly'}],series_tone:[{id:'tone_scifi'},{id:'tone_mystery'}],relationship:[{id:'rel_leader'},{id:'rel_healer'}],communication:[{id:'comm_rational'},{id:'comm_reserved'}],values:[{id:'val_protective'},{id:'val_utilitarian'},{id:'val_independent'}],hair:[{id:'hair_white'},{id:'hair_long'}],body:[{id:'body_tall'},{id:'body_average'}],eye:[{id:'eye_brown'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_sharp'},{id:'expr_lazy'}],special:[]}},
  {id:touhouIdBase+20,name:'上白泽慧音',name_native:'上白沢慧音',source_anime:'东方Project',source_type:'GAME',favourites:9500,image:'',description:'人里的寺子屋老师，半兽人。平时是温和的教学先生，满月之夜会变成白泽形态。能吞噬（隐藏）和创造（改写）历史。银色长发+书本要素，认真的知性美人。',tags:{personality:[{id:'gentle',level:0.8},{id:'mature',level:0.7},{id:'tsundere',level:0.3}],age_visual:[{id:'age_v_teen'}],age_aura:[{id:'age_a_senpai'}],role:[{id:'student'},{id:'class_officer'},{id:'mage'}],series_tone:[{id:'tone_scifi'},{id:'tone_healing'}],relationship:[{id:'rel_healer'},{id:'rel_equal'}],communication:[{id:'comm_reserved'},{id:'comm_rational'}],values:[{id:'val_kindness'},{id:'val_protective'},{id:'val_justice'}],hair:[{id:'hair_white'},{id:'hair_long'}],body:[{id:'body_average'}],eye:[{id:'eye_purple'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_gentle'}],special:[{id:'sp_horn'}]}},
  {id:touhouIdBase+21,name:'秦心',name_native:'秦こころ',source_anime:'东方Project',source_type:'GAME',favourites:9200,image:'',description:'操控感情的面灵气。平时无表情，通过切换面具来改变情绪和战斗风格。粉色双马尾+蓝白巫女服，是东方后来居上的高人气萝莉角色。',tags:{personality:[{id:'no_expression',level:0.9},{id:'kuudere',level:0.5},{id:'airhead',level:0.5}],age_visual:[{id:'age_v_loli'}],age_aura:[{id:'age_a_kouhai'}],role:[{id:'godly'},{id:'mage'}],series_tone:[{id:'tone_scifi'},{id:'tone_comedy'}],relationship:[{id:'rel_dependent'},{id:'rel_equal'}],communication:[{id:'comm_silent'}],values:[{id:'val_kindness'},{id:'val_freedom'}],hair:[{id:'hair_red'},{id:'hair_twintail'}],body:[{id:'body_petite'},{id:'body_loli_height'}],eye:[{id:'eye_purple'}],wardrobe:[{id:'cloth_kimono'}],expression:[{id:'expr_empty'}],special:[]}},
  {id:touhouIdBase+22,name:'伊吹萃香',name_native:'伊吹萃香',source_anime:'东方Project',source_type:'GAME',favourites:8800,image:'',description:'幻想乡最著名的鬼族之一。操纵密度的能力，能聚散自如。头顶双角，手戴锁链，嗜酒如命。性格豪爽不做作，是独居深山的酒鬼萝莉。',tags:{personality:[{id:'genki',level:0.9},{id:'airhead',level:0.6},{id:'comedic',level:0.5}],age_visual:[{id:'age_v_loli'}],age_aura:[{id:'age_a_kouhai'}],role:[{id:'godly'},{id:'wanderer'}],series_tone:[{id:'tone_comedy'},{id:'tone_scifi'}],relationship:[{id:'rel_buddy'}],communication:[{id:'comm_frank'}],values:[{id:'val_freedom'},{id:'val_independent'}],hair:[{id:'hair_brown'},{id:'hair_long'}],body:[{id:'body_petite'},{id:'body_loli_height'}],eye:[{id:'eye_brown'}],wardrobe:[{id:'cloth_casual'}],expression:[{id:'expr_lazy'},{id:'expr_bright'}],special:[{id:'sp_horn'}]}}];

// 合并东方角色
touhou.forEach(function(c) { db.push(c); });

// ═══ 写入文件 ═══
fs.writeFileSync(OUT_JSON, JSON.stringify(db, null, 2), 'utf-8');
fs.writeFileSync(OUT_JS, 'window.WAIFU_DB = ' + JSON.stringify(db) + ';', 'utf-8');

console.log('Done!');
console.log('Total characters:', db.length, '(original + touhou + hololive)');
console.log('Output:', OUT_JSON);
console.log('Output:', OUT_JS);
